zookeeper:
  address: 10.201.30.129:2181,10.201.30.193:2181,10.201.30.71:2181
  sessionTimeoutMs: 2000
  connectionTimeoutMs: 2000

spring:
  application:
    name: demo_zpf
  datasource:
    ga:
      jdbc-url: jdbc:mysql://10.201.30.71:3306/ga_system?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=utf-8
      username: ${GA_LOG_USER_NAME:remote}
      password: ${GA_LOG_PASSWD:aE5MriESSib>Q}
      driver-class-name: com.mysql.jdbc.Driver
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DemoJob
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc

quartz:
  cronExpression: 0/5 * 8-20 * * ?